#!/bin/bash

for man in socket netdevice
do
  # Script vim
  cat <<EOF > s1
:%s/\n\n^\([A-Z_]\{5,\}\) /\r\r===== \1\r\r/
:wq
EOF

  # If the txt file exists the automatic edition is ignored
  if [ ! -f "$man.txt" ]; then
    man 7 $man | pandoc -f man -t plain > $man.txt
    vim -s s1 $man.txt
  fi
  rm s1

  csplit $man.txt '/===== /' '{*}'

  for i in xx*
  do
    filename=$( sed -n "s/^===== //p" "$i" )
    if [ -n "$filename" ] && [ ! -f "$filename" ]; then
      echo "Processing $filename"
      mv "$i" "$filename"
      sed -i "s/^===== //" "$filename"
    else
      echo "Ignoring $filename"
      rm "$i"
    fi
  done
done
