#!/bin/bash

for man in socket netdevice open gai_strerror
do
  # Script vim
  cat <<EOF > s1
:%s/\n\n^\([A-Z_]\{5,\}\) /\r\r===== \1\r\r/
:wq
EOF

  # If the txt file exists the automatic edition is ignored
  for n in 2 3 7
  do
    # man 7 $man || man 2 $man | pandoc -f man -t plain > $man.txt
    if [ ! -f "${man}$n" ]; then
      man $n $man | pandoc -f man -t plain > ${man}$n
      vim -s s1 ${man}$n
    fi
  done
  rm s1

  for n in 2 3 7
  do
    if [ -f "${man}$n" ]; then
      csplit ${man}$n '/===== /' '{*}'
      for i in xx*
      do
        filename=$( sed -n "s/^===== //p" "$i" )
        if [ -n "$filename" ] && [ ! -f "$filename" ]; then
          echo "Processing $filename"
          mv "$i" "$filename"
          sed -i "s/^===== //" "$filename"
        else
          echo "Ignoring $filename"
          rm "$i"
        fi
      done
    fi
  done
done

# Remove section title
for i in ATTRIBUTES COLOPHON CONFORMING DESCRIPTION EXAMPLES FILES NOTES RETURN SYNOPSIS VERSIONS
do
  rm -f "$i"
done

# Remove arquivos vazios
find . -type f -size 1c -delete
